import { event } from './config.js';
import { request, ticketUrl } from './platform.js';
import { setupAccess } from './access.js';
let actor,tickets=[],issueRequest='';
const status=document.querySelector('#admin-status');
const labels={pending:'Pendiente',valid:'Aprobada',used:'Utilizada',cancelled:'Invalidada'};
const initialSellers=['Angélica','Jesús','Diego','Lucía','Sebastián','César'];
const roleNames={seller:'Vendedor',validator:'Validador'};
const random=()=>[...crypto.getRandomValues(new Uint8Array(16))].map(b=>b.toString(16).padStart(2,'0')).join('');
const packageName=id=>event.packages.find(p=>p.id===id)?.name||id;
function cell(text){const td=document.createElement('td');td.textContent=text;return td;}
function link(text,url){const a=document.createElement('a');a.textContent=text;a.href=url;a.className='secondary';a.target='_blank';a.rel='noopener';return a;}
async function copy(text){try{await navigator.clipboard.writeText(text);status.textContent='Copiado.';}catch{status.textContent='No se pudo copiar. Abre el enlace y copia su dirección.';}}
function render(){
  document.querySelector('#total-count').textContent=tickets.length;
  document.querySelector('#valid-count').textContent=tickets.filter(t=>t.status==='valid').length;
  document.querySelector('#used-count').textContent=tickets.filter(t=>t.status==='used').length;
  const own=tickets.filter(t=>t.sellerId===actor.id);document.querySelector('#own-sales').textContent=`Tus QR: ${own.length} generados · ${own.filter(t=>['valid','used'].includes(t.status)).length} ventas aprobadas`;
  const search=document.querySelector('#ticket-search').value.trim().toLowerCase(),filter=document.querySelector('#ticket-filter').value;
  const rows=document.querySelector('#ticket-rows');rows.replaceChildren();
  const makeRow=t=>{
    const row=document.createElement('tr'),actions=cell('');
    actions.append(link('Ver QR',ticketUrl(t.token)));
    const copyButton=document.createElement('button');copyButton.className='secondary';copyButton.textContent='Copiar enlace';copyButton.onclick=()=>copy(`Tu entrada de Shadow Fest\n${ticketUrl(t.token)}\nEl ingreso requiere aprobación de la organización.`);actions.append(copyButton);
    if(t.status==='pending'&&t.sellerId===actor.id){for(const [action,text,done] of [['markSent','Marcar enviado',t.sentAt],['requestApproval','Solicitar aprobación',t.approvalRequestedAt]]){if(done)continue;const button=document.createElement('button');button.className='secondary';button.textContent=text;button.onclick=async()=>{try{await request(action,{id:t.id});status.textContent=action==='markSent'?'Enlace marcado como enviado.':'Solicitud enviada al admin. Todavía no está aprobada.';await refresh();}catch(e){status.textContent=e.message;}};actions.append(button);}}
    if(actor.role==='supreme'&&t.status==='pending'){const approve=document.createElement('button');approve.className='secondary';approve.textContent='Aprobar venta';approve.onclick=async()=>{try{await request('approve',{id:t.id});await refresh();}catch(e){status.textContent=e.message;}};actions.append(approve);}
    if(actor.role==='supreme'&&['pending','valid'].includes(t.status)){const cancel=document.createElement('button');cancel.className='secondary';cancel.textContent='Invalidar';cancel.onclick=async()=>{if(!confirm('¿Invalidar esta entrada? Si estaba aprobada, se descontará del contador.'))return;try{await request('cancel',{id:t.id});await refresh();}catch(e){status.textContent=e.message;}};actions.append(cancel);}
    row.append(cell(t.buyer?.name?`${t.buyer.name} · ${t.buyer.registeredAt?'Registrado por cliente':'Ingresado al generar'}`:'Cliente sin nombre'),cell(t.buyer?.phone||'—'),cell(t.sellerName),cell(packageName(t.packageId)),cell(`${labels[t.status]} · ${t.sentAt?'Enviado':'Sin marcar envío'}${t.approvalRequestedAt?' · Pago por revisar':''}`),actions);return row;
  };
  tickets.filter(t=>(filter==='all'||(filter==='requested'?t.status==='pending'&&t.approvalRequestedAt:t.status===filter))&&(!search||`${t.buyer?.name||''} ${t.buyer?.phone||''} ${t.sellerName} ${t.id}`.toLowerCase().includes(search))).slice().reverse().forEach(t=>rows.append(makeRow(t)));
  const queue=document.querySelector('#approval-rows');queue.replaceChildren();const waiting=tickets.filter(t=>t.status==='pending'&&t.approvalRequestedAt);document.querySelector('#approval-count').textContent=waiting.length;if(actor.role==='supreme'){waiting.forEach(t=>queue.append(makeRow(t)));if(!waiting.length){const tr=document.createElement('tr'),td=cell('No hay pagos solicitados por revisar.');td.colSpan=6;tr.append(td);queue.append(tr);}}
  if(!rows.children.length){const row=document.createElement('tr'),td=cell('Aún no hay entradas que coincidan.');td.colSpan=6;row.append(td);rows.append(row);}
}
async function refresh(){tickets=await request('list');render();if(actor.role==='supreme'){const stats=await request('stats');document.querySelector('#sold-admin').textContent=stats.sold;await renderAccesses();}}
async function renderAccesses(){const rows=document.querySelector('#access-list');rows.replaceChildren();(await request('accessList')).forEach(a=>{const row=document.createElement('div');row.className='access-row';const text=document.createElement('span');text.textContent=`${a.name} · ${roleNames[a.role]} · ${a.active?'Activo':'Revocado'}`;row.append(text);if(a.role==='seller'){const own=tickets.filter(t=>t.sellerId===a.id);const summary=document.createElement('small');summary.className='seller-summary';summary.textContent=`${own.length} generados · ${own.filter(t=>t.status==='pending').length} pendientes · ${own.filter(t=>['valid','used'].includes(t.status)).length} ventas aprobadas · ${own.filter(t=>t.status==='cancelled').length} invalidados`;text.append(document.createElement('br'),summary);}if(a.active){const button=document.createElement('button');button.className='secondary';button.textContent='Revocar';button.onclick=async()=>{try{await request('accessRevoke',{id:a.id});await renderAccesses();}catch(e){status.textContent=e.message;}};row.append(button);}rows.append(row);});}
document.querySelector('#initial-seller-names').textContent=initialSellers.join(' · ');
document.querySelector('#create-initial-sellers').onclick=async e=>{const button=e.currentTarget;button.disabled=true;const output=document.querySelector('#initial-seller-results');try{const existing=await request('accessList');const normalize=n=>n.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();for(const name of initialSellers){if(existing.some(a=>a.role==='seller'&&normalize(a.name)===normalize(name)))continue;const code=random();const result=await request('accessCreate',{name,code,role:'seller'});existing.push({id:result.id,name,role:'seller'});const line=document.createElement('p');const title=document.createElement('strong');title.textContent=name;const secret=document.createElement('code');secret.textContent=code;line.append(title,' — ',secret);output.append(line);}document.querySelector('#create-access-status').textContent='Equipo preparado. Copia los códigos nuevos y entrégalos por privado; solo se muestran aquí hasta recargar.';await renderAccesses();}catch(error){document.querySelector('#create-access-status').textContent=error.message;}finally{button.disabled=false;}};
event.packages.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;document.querySelector('#issue-package').append(o);});
setupAccess(['supreme','seller'],async current=>{actor=current;document.querySelector('#issue-help').textContent=actor.role==='supreme'?'Los QR que generas quedan asignados a ti. Aprueba la venta cuando compruebes el pago.':'Los QR quedan asignados a ti. Marca el enlace enviado y solicita aprobación cuando el cliente te confirme que pagó.';document.querySelectorAll('[data-supreme]').forEach(n=>n.classList.toggle('hidden',actor.role!=='supreme'));await refresh();});
document.querySelector('#issue-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;const feedback=document.querySelector('#issue-status');try{issueRequest ||=random();const data=new FormData(e.target);await request('issue',{packageId:data.get('package'),name:data.get('name'),requestId:issueRequest});issueRequest='';e.target.reset();feedback.textContent='QR generados y asignados. Quedan pendientes de aprobación del único admin.';await refresh();}catch(error){feedback.textContent=error.message;}finally{button.disabled=false;}});
document.querySelector('#issue-package').addEventListener('change',()=>issueRequest='');
document.querySelector('#create-access').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button[type=submit]');button.disabled=true;const f=new FormData(e.target);try{await request('accessCreate',{name:f.get('name'),code:f.get('code'),role:f.get('role')});document.querySelector('#create-access-status').textContent='Acceso creado. Entrega el código de forma privada; no se mostrará nuevamente.';e.target.reset();await renderAccesses();}catch(error){document.querySelector('#create-access-status').textContent=error.message;}finally{button.disabled=false;}});
document.querySelector('#generate-access-code').onclick=()=>{document.querySelector('#seller-code').value=random();};
document.querySelector('#ticket-search').oninput=render;document.querySelector('#ticket-filter').onchange=render;
document.querySelector('#refresh-tickets').onclick=()=>refresh().catch(e=>status.textContent=e.message);
window.addEventListener('storage',()=>{if(actor)refresh().catch(e=>status.textContent=e.message);});
setInterval(()=>{if(actor&&!document.hidden)refresh().catch(e=>status.textContent=e.message);},30000);
document.querySelector('#export-tickets').onclick=()=>{const escape=v=>{let text=String(v??'');if(/^[=+@\-\t\r]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';};const rows=[['Comprador','Teléfono','Vendedor','Paquete','Estado','Emitida','Registro','Ingreso'],...tickets.map(t=>[t.buyer?.name,t.buyer?.phone,t.sellerName,t.packageId,labels[t.status],t.createdAt,t.buyer?.registeredAt,t.usedAt])];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(escape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='shadowfest-entradas.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
