import {withBusy,isBusy} from './busy.js?v=20261006b';
import { event } from './config.js?v=20261006b';
import { request, ticketUrl } from './platform.js?v=20261006b';
import { setupAccess } from './access.js?v=20261006b';
let actor,tickets=[],issueRequest='';
const status=document.querySelector('#admin-status');
const labels={pending:'Pendiente',valid:'Aprobada',used:'Utilizada',cancelled:'Invalidada'};
const initialSellers=['Angélica','Jesús','Diego','Lucía','Sebastián','César'];
const roleNames={seller:'Vendedor',validator:'Validador'};
const random=()=>[...crypto.getRandomValues(new Uint8Array(16))].map(b=>b.toString(16).padStart(2,'0')).join('');
async function ticketAction(button,id,action){return withBusy(button,'Procesando…',async()=>{const peers=[...document.querySelectorAll(`[data-ticket-id="${id}"]`)];peers.forEach(b=>b.disabled=true);try{await request(action,{id});status.textContent=action==='requestApproval'?'Solicitud enviada. Pago pendiente de revisión.':action==='markSent'?'Enlace marcado como enviado.':'Cambio guardado.';await refresh();}catch(e){status.textContent=e.message;}finally{peers.forEach(b=>b.disabled=false);}},'ticket:'+id);}
const packageName=id=>event.packages.find(p=>p.id===id)?.name||id;
function cell(text){const td=document.createElement('td');td.textContent=text;return td;}
function link(text,url){const a=document.createElement('a');a.textContent=text;a.href=url;a.className='secondary';a.target='_blank';a.rel='noopener';return a;}
async function copy(text){try{await navigator.clipboard.writeText(text);status.textContent='Copiado.';}catch{status.textContent='No se pudo copiar. Abre el enlace y copia su dirección.';}}
function render(){
  document.querySelector('#total-count').textContent=tickets.length;
  document.querySelector('#valid-count').textContent=tickets.filter(t=>t.status==='valid').length;
  document.querySelector('#used-count').textContent=tickets.filter(t=>t.status==='used').length;
  const own=tickets.filter(t=>t.sellerId===actor.id);document.querySelector('#own-sales').textContent=`Tus QR: ${own.length} generados · ${own.filter(t=>['valid','used'].includes(t.status)).length} ventas aprobadas`;
  const search=document.querySelector('#ticket-search').value.trim().toLowerCase(),filter=document.querySelector('#ticket-filter').value;
  const rows=document.querySelector('#ticket-rows');rows.replaceChildren();
  const makeRow=t=>{
    const row=document.createElement('tr'),actions=cell('');
    const code=document.createElement('strong');code.className='entry-short-code';code.textContent=t.shortCode||'QR anterior';actions.append(code,link('Ver QR',ticketUrl(t.token)));
    const copyButton=document.createElement('button');copyButton.className='secondary';copyButton.textContent='Copiar enlace';copyButton.onclick=()=>withBusy(copyButton,'Copiando…',()=>copy(`Tu entrada de Shadow Fest\nCódigo de puerta: ${t.shortCode||'Ver QR'}\n${ticketUrl(t.token)}\nEl ingreso requiere aprobación de la organización.`));actions.append(copyButton);
    if(t.status==='pending'&&t.sellerId===actor.id){for(const [action,text,done] of [['markSent','Marcar enviado',t.sentAt],['requestApproval','Solicitar aprobación',t.approvalRequestedAt]]){if(done)continue;const button=document.createElement('button');button.className='secondary';button.textContent=text;button.dataset.ticketId=t.id;button.onclick=()=>ticketAction(button,t.id,action);actions.append(button);}}
    if(actor.role==='supreme'&&t.status==='pending'){const approve=document.createElement('button');approve.className='secondary';approve.textContent='Aprobar venta';approve.dataset.ticketId=t.id;approve.onclick=()=>ticketAction(approve,t.id,'approve');actions.append(approve);}
    if(actor.role==='supreme'&&['pending','valid'].includes(t.status)){const cancel=document.createElement('button');cancel.className='secondary';cancel.textContent='Invalidar';cancel.dataset.ticketId=t.id;cancel.onclick=()=>{if(confirm('¿Invalidar esta entrada? Si estaba aprobada, se descontará del contador.'))return ticketAction(cancel,t.id,'cancel');};actions.append(cancel);}
    row.append(cell(t.buyer?.name?`${t.buyer.name} · ${t.buyer.registeredAt?'Registrado por cliente':'Ingresado al generar'}`:'Cliente sin nombre'),cell(t.buyer?.phone||'—'),cell(t.sellerName),cell(packageName(t.packageId)),cell(`${labels[t.status]} · ${t.sentAt?'Enviado':'Sin marcar envío'}${t.approvalRequestedAt?' · Pago por revisar':''}`),actions);return row;
  };
  tickets.filter(t=>(filter==='all'||(filter==='requested'?t.status==='pending'&&t.approvalRequestedAt:t.status===filter))&&(!search||`${t.buyer?.name||''} ${t.buyer?.phone||''} ${t.sellerName} ${t.shortCode||''} ${t.id}`.toLowerCase().includes(search))).slice().reverse().forEach(t=>rows.append(makeRow(t)));
  const queue=document.querySelector('#approval-rows');queue.replaceChildren();const waiting=tickets.filter(t=>t.status==='pending'&&t.approvalRequestedAt);document.querySelector('#approval-count').textContent=waiting.length;if(actor.role==='supreme'){waiting.forEach(t=>queue.append(makeRow(t)));if(!waiting.length){const tr=document.createElement('tr'),td=cell('No hay pagos solicitados por revisar.');td.colSpan=6;tr.append(td);queue.append(tr);}}
  if(!rows.children.length){const row=document.createElement('tr'),td=cell('Aún no hay entradas que coincidan.');td.colSpan=6;row.append(td);rows.append(row);}
}
async function refresh(){tickets=await request('list');render();if(actor.role==='supreme'){const stats=await request('stats');document.querySelector('#sold-admin').textContent=stats.sold;await renderAccesses();}}
async function renderAccesses(){const rows=document.querySelector('#access-list');rows.replaceChildren();(await request('accessList')).forEach(a=>{const row=document.createElement('div');row.className='access-row';const text=document.createElement('span');text.textContent=`${a.name} · ${roleNames[a.role]} · ${a.active?'Activo':'Revocado'}`;row.append(text);if(a.role==='seller'){const own=tickets.filter(t=>t.sellerId===a.id);const summary=document.createElement('small');summary.className='seller-summary';summary.textContent=`${own.length} generados · ${own.filter(t=>t.status==='pending').length} pendientes · ${own.filter(t=>['valid','used'].includes(t.status)).length} ventas aprobadas · ${own.filter(t=>t.status==='cancelled').length} invalidados`;text.append(document.createElement('br'),summary);}if(a.active){const button=document.createElement('button');button.className='secondary';button.textContent='Revocar';button.onclick=()=>withBusy(button,'Revocando…',async()=>{try{await request('accessRevoke',{id:a.id});await renderAccesses();}catch(e){status.textContent=e.message;}});row.append(button);}rows.append(row);});}
document.querySelector('#initial-seller-names').textContent=initialSellers.join(' · ');
document.querySelector('#create-initial-sellers').onclick=async e=>{const button=e.currentTarget;button.disabled=true;const original=button.textContent;button.textContent='Creando vendedores…';button.setAttribute('aria-busy','true');const output=document.querySelector('#initial-seller-results');try{const existing=await request('accessList');const normalize=n=>n.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();for(const name of initialSellers){if(existing.some(a=>a.role==='seller'&&normalize(a.name)===normalize(name)))continue;const code=random();const result=await request('accessCreate',{name,code,role:'seller'});existing.push({id:result.id,name,role:'seller'});const line=document.createElement('p');const title=document.createElement('strong');title.textContent=name;const secret=document.createElement('code');secret.textContent=code;line.append(title,' — ',secret);output.append(line);}document.querySelector('#create-access-status').textContent='Equipo preparado. Copia los códigos nuevos y entrégalos por privado; solo se muestran aquí hasta recargar.';await renderAccesses();}catch(error){document.querySelector('#create-access-status').textContent=error.message;}finally{button.disabled=false;button.textContent=original;button.removeAttribute('aria-busy');}};
event.packages.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;document.querySelector('#issue-package').append(o);});
setupAccess(['supreme','seller'],async current=>{actor=current;document.querySelector('#issue-help').textContent=actor.role==='supreme'?'Los QR que generas quedan asignados a ti. Aprueba la venta cuando compruebes el pago.':'Los QR quedan asignados a ti. Marca el enlace enviado y solicita aprobación cuando el cliente te confirme que pagó.';document.querySelectorAll('[data-supreme]').forEach(n=>n.classList.toggle('hidden',actor.role!=='supreme'));await refresh();});
document.querySelector('#issue-form').addEventListener('submit',e=>{e.preventDefault();const form=e.target,button=form.querySelector('button[type=submit]');return withBusy(button,'Generando…',async()=>{const feedback=document.querySelector('#issue-status'),controls=[...form.querySelectorAll('input,select')];const data=new FormData(form);controls.forEach(n=>n.disabled=true);try{issueRequest ||=random();feedback.textContent='Guardando las entradas…';const result=await request('issue',{packageId:data.get('package'),quantity:Number(data.get('quantity')),name:data.get('name'),requestId:issueRequest,onProgress:(done,total)=>{feedback.textContent=`Guardando ${done} de ${total} entradas…`;}});issueRequest='';form.reset();feedback.textContent=`${result.quantity||1} entradas generadas y asignadas. Pendientes de aprobación.`;await refresh();}catch(error){feedback.textContent=error.message+' Puedes reintentar; se conserva la solicitud para evitar duplicados.';}finally{controls.forEach(n=>n.disabled=false);updateQuantity();}},'issue');});
function updateQuantity(){const pack=document.querySelector('#issue-package').value==='crew';document.querySelector('#issue-quantity').disabled=pack;document.querySelector('#quantity-help').textContent=pack?'El pack genera 6 QR individuales.':'Lote de entradas individuales, sin beneficio del pack de 6.';}
document.querySelector('#issue-package').addEventListener('change',()=>{issueRequest='';updateQuantity();});document.querySelector('#issue-quantity').addEventListener('change',()=>issueRequest='');document.querySelector('#issue-form input[name=name]').addEventListener('input',()=>issueRequest='');
document.querySelector('#create-access').addEventListener('submit',e=>{e.preventDefault();const form=e.target,f=new FormData(form);return withBusy(form.querySelector('button[type=submit]'),'Creando acceso…',async()=>{try{await request('accessCreate',{name:f.get('name'),code:f.get('code'),role:f.get('role')});document.querySelector('#create-access-status').textContent='Acceso creado. Entrega el código de forma privada.';form.reset();await renderAccesses();}catch(error){document.querySelector('#create-access-status').textContent=error.message;}},'create-access');});
document.querySelector('#generate-access-code').onclick=()=>{document.querySelector('#seller-code').value=random();};
document.querySelector('#ticket-search').oninput=render;document.querySelector('#ticket-filter').onchange=render;
document.querySelector('#refresh-tickets').onclick=e=>withBusy(e.currentTarget,'Actualizando…',()=>refresh().catch(err=>status.textContent=err.message));
window.addEventListener('storage',()=>{if(actor&&!isBusy())refresh().catch(e=>status.textContent=e.message);});
setInterval(()=>{if(actor&&!document.hidden&&!isBusy())refresh().catch(e=>status.textContent=e.message);},30000);
document.querySelector('#export-tickets').onclick=()=>{const escape=v=>{let text=String(v??'');if(/^[=+@\-\t\r]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';};const rows=[['Comprador','Teléfono','Vendedor','Paquete','Código puerta','Estado','Emitida','Registro','Ingreso'],...tickets.map(t=>[t.buyer?.name,t.buyer?.phone,t.sellerName,t.packageId,t.shortCode,labels[t.status],t.createdAt,t.buyer?.registeredAt,t.usedAt])];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(escape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='shadowfest-entradas.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
