import {withBusy} from './busy.js?v=20261006b';
import { event } from './config.js?v=20261006b';
import { request, extractCode, ticketUrl, showMode, localDemo } from './platform.js?v=20261006b';
showMode();const status=document.querySelector('#qr-status');let code='',shortCode='';
async function render(){document.querySelector('#copy-short-code').classList.add('hidden');document.querySelector('#buyer-name-form').classList.add('hidden');const box=document.querySelector('#qr-box');box.classList.add('hidden');document.querySelector('#copy-ticket').classList.add('hidden');try{code=extractCode(location.hash.slice(1));const t=await request('ticket',{code});document.querySelector('#buyer-name-form').classList.toggle('hidden',t.registered||!['pending','valid'].includes(t.status));shortCode=t.shortCode||'';document.querySelector('#ticket-code').textContent=shortCode;document.querySelector('#copy-short-code').classList.toggle('hidden',!shortCode||!['pending','valid'].includes(t.status));document.querySelector('#guest-name').textContent=t.name;document.querySelector('#guest-package').textContent=event.packages.find(p=>p.id===t.packageId)?.name||'';if(!['pending','valid'].includes(t.status))throw new Error(t.status==='used'?'Entrada utilizada. No permite un segundo ingreso.':'Entrada anulada.');box.replaceChildren();new window.QRCode(box,{text:t.shortCode||ticketUrl(code),width:220,height:220,correctLevel:window.QRCode.CorrectLevel.M});box.classList.remove('hidden');document.querySelector('#copy-ticket').classList.remove('hidden');status.textContent=t.status==='pending'?'QR generado. Pendiente de aprobación: todavía no permite ingresar.':localDemo?'QR de prueba aprobado.':'Entrada aprobada. Presenta tu documento y este QR en puerta.';status.className=t.status==='pending'?'status pending':'status valid';}catch(error){status.textContent=error.message;status.className='status error';}}
document.querySelector('#copy-ticket').onclick=async()=>{try{await navigator.clipboard.writeText(ticketUrl(code));status.textContent='Enlace copiado.';}catch{status.textContent='Copia la dirección del navegador.';}};
document.querySelector('#buyer-name-form').onsubmit=e=>{e.preventDefault();const form=e.target,data=new FormData(form);return withBusy(form.querySelector('button'),'Guardando nombre…',async()=>{try{await request('buyerName',{code,name:data.get('name'),consent:data.get('consent')==='on'});await render();}catch(error){document.querySelector('#buyer-name-status').textContent=error.message;}},'buyer-name');};
window.addEventListener('storage',render);render();

document.querySelector('#copy-short-code').onclick=e=>withBusy(e.currentTarget,'Copiando…',async()=>{try{await navigator.clipboard.writeText(shortCode);status.textContent='Código de puerta copiado: '+shortCode;}catch{status.textContent='Código de puerta: '+shortCode;}});
