import { event } from './config.js?v=20261006b';
import { request, extractCode } from './platform.js?v=20261006b';
import { setupAccess } from './access.js?v=20261006b';
import { withBusy } from './busy.js?v=20261006b';
import QrScanner from './vendor/qr-scanner.min.js?v=20261006b';
setupAccess(['supreme','validator'],async()=>{});
let currentCode='',scanner=null,scanGeneration=0,lookupGeneration=0;
const video=document.querySelector('#scanner-video'),scanStatus=document.querySelector('#scan-status'),feedback=document.querySelector('#validation-status'),confirmButton=document.querySelector('#confirm-entry'),lookupButton=document.querySelector('#lookup-form button'),startButton=document.querySelector('#start-camera');
async function lookup(value){const generation=++lookupGeneration;currentCode='';confirmButton.disabled=true;document.querySelector('#scan-result').classList.remove('hidden');document.querySelector('#scan-name').textContent='Consultando…';document.querySelector('#scan-package').textContent='';feedback.textContent='Verificando la entrada en Firebase…';try{const code=extractCode(value),ticket=await request('lookup',{code});if(generation!==lookupGeneration)return;document.querySelector('#scan-name').textContent=ticket.name;document.querySelector('#scan-package').textContent=`${event.packages.find(p=>p.id===ticket.packageId)?.name||''} · ${ticket.shortCode||'QR anterior'}`;if(ticket.status==='pending')throw new Error('Pendiente de aprobación del admin. No autorizar ingreso.');if(ticket.status==='used')throw new Error('QR ya utilizado. No autorizar ingreso.');if(ticket.status!=='valid')throw new Error('Entrada invalidada. No autorizar ingreso.');currentCode=ticket.token;confirmButton.disabled=false;feedback.textContent='Entrada aprobada. Confirma cuando el asistente esté en puerta.';feedback.className='status valid';}catch(e){if(generation!==lookupGeneration)return;if(document.querySelector('#scan-name').textContent==='Consultando…')document.querySelector('#scan-name').textContent='Entrada no disponible';feedback.textContent=e.message;feedback.className='status error';}}
async function consult(value){stopCamera();return withBusy(lookupButton,'Consultando…',()=>lookup(value),'lookup');}
document.querySelector('#lookup-form').onsubmit=e=>{e.preventDefault();consult(document.querySelector('#code-input').value);};
document.querySelector('#code-input').oninput=()=>{lookupGeneration++;currentCode='';confirmButton.disabled=true;document.querySelector('#scan-result').classList.add('hidden');};
confirmButton.onclick=()=>{if(!currentCode)return;const code=currentCode;return withBusy(confirmButton,'Registrando ingreso…',async()=>{currentCode='';try{await request('validate',{code});feedback.textContent='INGRESO REGISTRADO. No permite un segundo acceso.';feedback.className='status valid';document.querySelector('#code-input').value='';}catch(e){feedback.textContent=e.message;feedback.className='status error';}},'admit').finally(()=>{confirmButton.disabled=true;});};
function stopCamera(){scanGeneration++;scanner?.destroy();scanner=null;video.classList.add('hidden');document.querySelector('#stop-camera').classList.add('hidden');startButton.disabled=false;}
document.querySelector('#stop-camera').onclick=stopCamera;
startButton.onclick=()=>withBusy(startButton,'Abriendo cámara…',async()=>{stopCamera();startButton.disabled=true;lookupGeneration++;currentCode='';confirmButton.disabled=true;document.querySelector('#scan-result').classList.add('hidden');const generation=scanGeneration;try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Abre esta página en Safari o Chrome y permite el uso de cámara. También puedes usar una foto o el código de 6 caracteres.');video.classList.remove('hidden');scanner=new QrScanner(video,result=>{if(generation!==scanGeneration)return;const value=result.data;document.querySelector('#code-input').value=value;scanStatus.textContent='QR leído. Consultando entrada…';consult(value);},{preferredCamera:'environment',maxScansPerSecond:8,returnDetailedScanResult:true});await scanner.start();if(generation!==scanGeneration)return;document.querySelector('#stop-camera').classList.remove('hidden');scanStatus.textContent='Apunta al QR. Revisa el resultado antes de confirmar.';}catch(e){stopCamera();scanStatus.textContent=e.name==='NotAllowedError'?'Permite la cámara en los ajustes del navegador, o usa una foto/código manual.':e.message||String(e);}},'camera').finally(()=>{startButton.disabled=!!scanner;});
document.querySelector('#qr-photo').onchange=e=>{const file=e.target.files?.[0];if(!file)return;return withBusy(document.querySelector('#photo-label'),'Leyendo foto…',async()=>{stopCamera();try{const result=await QrScanner.scanImage(file,{returnDetailedScanResult:true});document.querySelector('#code-input').value=result.data;await consult(result.data);scanStatus.textContent='QR leído desde la foto.';}catch{scanStatus.textContent='No se encontró un QR legible en la imagen. Usa otra foto o escribe los 6 caracteres.';}finally{e.target.value='';}},'photo');};
window.addEventListener('pagehide',stopCamera);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();});
