import test from 'node:test';
import assert from 'node:assert/strict';
import { createService } from '../service.js';
// Transactional in-memory adapter: exercises the real server service without a cloud project.
function database(){
  const docs=new Map();let queue=Promise.resolve();
  const clone=value=>value===undefined?undefined:structuredClone(value);
  function snapshot(path){const data=clone(docs.get(path));return {id:path.split('/').at(-1),exists:data!==undefined,data:()=>{if(data?.expiresAt instanceof Date)data.expiresAt={toMillis:()=>docs.get(path).expiresAt.getTime()};return data;}};}
  const ref=path=>({id:path.split('/').at(-1),path,collection:name=>collection(path+'/'+name),get:async()=>snapshot(path),set:async v=>docs.set(path,clone(v)),update:async v=>{assert.ok(docs.has(path));docs.set(path,{...docs.get(path),...clone(v)});},delete:async()=>docs.delete(path)});
  function collection(path,condition){return {doc:id=>ref(path+'/'+id),where:(field,op,value)=>collection(path,{field,value}),get:async()=>({docs:[...docs.keys()].filter(k=>k.startsWith(path+'/')&&k.slice(path.length+1).split('/').length===1&&(!condition||docs.get(k)[condition.field]===condition.value)).map(snapshot)})};}
  return {collection,runTransaction(fn){const operation=queue.then(async()=>{const writes=[];const tx={get:r=>r.get(),set:(r,v)=>writes.push(()=>docs.set(r.path,clone(v))),create:(r,v)=>{assert.ok(!docs.has(r.path));writes.push(()=>docs.set(r.path,clone(v)));},update:(r,v)=>writes.push(()=>docs.set(r.path,{...docs.get(r.path),...clone(v)}))};const result=await fn(tx);writes.forEach(w=>w());return result;});queue=operation.catch(()=>{});return operation;}};
}
async function fixture(){const call=createService(database(),'test-supreme-secret');const supreme=await call('login',{code:'test-supreme-secret'});await call('accessCreate',{name:'Vendedor Uno',code:'seller-one-secret',role:'seller'},supreme.token);await call('accessCreate',{name:'Vendedor Dos',code:'seller-two-secret',role:'seller'},supreme.token);await call('accessCreate',{name:'Puerta',code:'door-access-secret',role:'validator'},supreme.token);return {call,supreme,seller:await call('login',{code:'seller-one-secret'}),other:await call('login',{code:'seller-two-secret'}),door:await call('login',{code:'door-access-secret'})};}
test('server rejects unauthenticated and unauthorized writes and isolates seller sales',async()=>{const {call,supreme,seller,other}=await fixture();await assert.rejects(call('issue',{paymentConfirmed:true,packageId:'general',requestId:'1'.repeat(32)}),/acceso/);await assert.rejects(call('accessCreate',{name:'Bad',code:'bad-code',role:'seller'},seller.token),/permiso/);await call('issue',{paymentConfirmed:true,packageId:'general',requestId:'1'.repeat(32)},seller.token);assert.equal((await call('list',{},other.token)).length,0);assert.equal((await call('list',{},supreme.token)).length,1);});
test('pack creates six independently claimable secure tickets and retry counts only once',async()=>{const {call,seller}=await fixture();const data={packageId:'crew',paymentConfirmed:true,requestId:'2'.repeat(32)};const [a,b]=await Promise.all([call('issue',data,seller.token),call('issue',data,seller.token)]);assert.equal(a.length,6);assert.deepEqual(a,b);assert.equal(new Set(a.map(t=>t.token)).size,6);assert.match(a[0].token,/^[a-f0-9]{64}$/);assert.match(a[0].claimCode,/^[a-f0-9]{32}$/);assert.equal((await call('stats')).sold,116);await assert.rejects(call('issue',{...data,packageId:'general'},seller.token),/otro paquete/);});
test('buyer registration is single-use, retains seller, and does not expose phone on public views',async()=>{const {call,seller,supreme}=await fixture();const [t]=await call('issue',{packageId:'general',paymentConfirmed:true,requestId:'3'.repeat(32)},seller.token);assert.deepEqual(await call('claimLookup',{code:t.claimCode}),{packageId:'general',registered:false});const data={code:t.claimCode,name:'Comprador Prueba',phone:'+51 955 111 222',adult:true,consent:true};const results=await Promise.allSettled([call('claim',data),call('claim',data)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const entry=(await call('list',{},supreme.token))[0];assert.equal(entry.buyer.name,'Comprador Prueba');assert.equal(entry.sellerId,seller.actor.id);assert.equal((await call('ticket',{code:t.token})).phone,undefined);await assert.rejects(call('claim',{...data,name:'Otra persona'}),/registrada/);assert.equal((await call('stats')).sold,111);});
test('only validators can admit, registered tickets enter once under concurrent calls',async()=>{const {call,seller,door}=await fixture();const [t]=await call('issue',{packageId:'general',paymentConfirmed:true,requestId:'4'.repeat(32)},seller.token);await assert.rejects(call('validate',{code:t.token},door.token),/pendiente/);await call('claim',{code:t.claimCode,name:'Comprador Prueba',phone:'955111222',adult:true,consent:true});await assert.rejects(call('validate',{code:t.token},seller.token),/permiso/);const result=await Promise.allSettled([call('validate',{code:t.token},door.token),call('validate',{code:t.token},door.token)]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);assert.equal((await call('stats')).sold,111);});
test('revocation invalidates existing sessions; cancellation decrements once and blocks claim',async()=>{const {call,seller,supreme}=await fixture();const [t]=await call('issue',{packageId:'general',paymentConfirmed:true,requestId:'5'.repeat(32)},seller.token);await assert.rejects(call('cancel',{id:t.id},seller.token),/permiso/);await call('cancel',{id:t.id},supreme.token);assert.equal((await call('stats')).sold,110);await assert.rejects(call('cancel',{id:t.id},supreme.token),/válidas/);await assert.rejects(call('claimLookup',{code:t.claimCode}),/anulada/);await call('accessRevoke',{id:seller.actor.id},supreme.token);await assert.rejects(call('list',{},seller.token),/revocado/);await assert.rejects(call('login',{code:'seller-one-secret'}),/revocado/);});
test('login throttles attempts and payment and consent are enforced on the server',async()=>{const {call,seller}=await fixture();await assert.rejects(call('issue',{packageId:'general',requestId:'6'.repeat(32)},seller.token),/pago/);for(let i=0;i<8;i++)await assert.rejects(call('login',{code:'wrong'},'','other-ip'),/incorrecto/);await assert.rejects(call('login',{code:'seller-one-secret'},'','other-ip'),/intentos/);const [t]=await call('issue',{packageId:'general',paymentConfirmed:true,requestId:'6'.repeat(32)},seller.token);await assert.rejects(call('claim',{code:t.claimCode,name:'Some buyer',phone:'955111222',adult:true,consent:false}),/confirmaciones/);});
