import {newShortCode} from '../ticket-code.js';
import { before, beforeEach, after, test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';
import { initializeTestEnvironment, assertFails, assertSucceeds } from '@firebase/rules-unit-testing';
import { doc, collection, getDoc, getDocs, setDoc, updateDoc, writeBatch, query, where, serverTimestamp, runTransaction } from 'firebase/firestore';
let env;
const r=(db,name,id)=>doc(db,`shadowfest_live/2026/${name}/${id}`);
const db=uid=>uid?env.authenticatedContext(uid).firestore():env.unauthenticatedContext().firestore();
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-shadowfest',firestore:{host:'127.0.0.1',port:8080,rules:await readFile(new URL('../firestore-live.rules',import.meta.url),'utf8')}});});
beforeEach(async()=>{await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{for(const [id,role] of [['admin','supreme'],['seller','seller'],['other','seller'],['door','validator']])await setDoc(r(c.firestore(),'staff',id),{name:id,role,active:true,createdAt:serverTimestamp()});});});
after(async()=>{await env?.cleanup();});
async function issue(uid='seller',count=1){const client=db(uid),ids=Array.from({length:count},()=>randomBytes(32).toString('hex')),base=uid+'_'+randomBytes(16).toString('hex'),packageId=count===6?'crew':'general';for(let offset=0;offset<count;offset+=3){const requestId=base+'_'+Math.floor(offset/3),part=ids.slice(offset,offset+3),batch=writeBatch(client);batch.set(r(client,'requests',requestId),{sellerId:uid,packageId,ids:part,quantity:count,createdAt:serverTimestamp()});for(const token of part){const shortCode=newShortCode();await getDoc(r(client,'codes',shortCode));batch.set(r(client,'tickets',token),{token,shortCode,sellerId:uid,sellerName:uid,packageId,status:'pending',buyer:null,createdAt:serverTimestamp(),usedAt:null,requestId});batch.set(r(client,'passes',token),{token,shortCode,name:'Sin nombre',packageId,status:'pending',registered:false});batch.set(r(client,'codes',shortCode),{token,sellerId:uid});}await batch.commit();}return ids;}
async function approve(id){const client=db('admin');await runTransaction(client,async tx=>{const sales=r(client,'meta','sales'),snap=await tx.get(sales),approved=(snap.exists()?snap.data().approved:0)+1;tx.update(r(client,'tickets',id),{status:'valid',approvedAt:serverTimestamp(),approvedBy:'admin'});tx.update(r(client,'passes',id),{status:'valid'});tx.set(sales,{approved,initialSold:110,lastTicket:id,updatedAt:serverTimestamp()});tx.set(r(client,'publicStats','sales'),{approved,initialSold:110,updatedAt:serverTimestamp()});});}
test('one and six ticket issuance succeeds, owner query is isolated, anonymous cannot enumerate',async()=>{const ids=await issue('seller',6);assert.equal(ids.length,6);const client=db('seller');assert.equal((await getDocs(query(collection(client,'shadowfest_live/2026/tickets'),where('sellerId','==','seller')))).size,6);await assertFails(getDocs(collection(client,'shadowfest_live/2026/tickets')));await assertFails(getDoc(r(db('other'),'tickets',ids[0])));await assertSucceeds(getDoc(r(db(),'passes',ids[0])));await assertFails(getDoc(r(db(),'tickets',ids[0])));await assertFails(getDocs(collection(db(),'shadowfest_live/2026/passes')));await assertFails(getDoc(r(db(),'meta','sales')));});
test('seller cannot forge approvals, reassign tickets or access another seller',async()=>{const [id]=await issue();await assertFails(updateDoc(r(db('seller'),'tickets',id),{status:'valid'}));await assertFails(updateDoc(r(db('seller'),'tickets',id),{sellerId:'other'}));await assertFails(updateDoc(r(db('other'),'tickets',id),{sentAt:serverTimestamp()}));await assertFails(setDoc(r(db('seller'),'staff','hacker'),{name:'hacker',role:'supreme',active:true,createdAt:serverTimestamp()}));await assertFails(setDoc(r(db('new-unprovisioned'),'staff','new-unprovisioned'),{name:'hacker',role:'seller',active:true,createdAt:serverTimestamp()}));});
test('delivery and request preserve pending, approval atomically counts exactly once',async()=>{const [id]=await issue();const client=db('seller');await updateDoc(r(client,'tickets',id),{sentAt:serverTimestamp()});await updateDoc(r(client,'tickets',id),{approvalRequestedAt:serverTimestamp(),approvalRequestedBy:'seller'});assert.equal((await getDoc(r(client,'tickets',id))).data().status,'pending');await assertFails(updateDoc(r(db('admin'),'tickets',id),{status:'valid',approvedAt:serverTimestamp(),approvedBy:'admin'}));await approve(id);assert.equal((await getDoc(r(db(),'publicStats','sales'))).data().approved,1);await assertFails(approve(id));await assertFails(setDoc(r(db('seller'),'publicStats','sales'),{approved:999,initialSold:110,updatedAt:serverTimestamp()}));await assertFails(updateDoc(r(db('admin'),'publicStats','sales'),{approved:999,updatedAt:serverTimestamp()}));});
test('optional name is single use, bound to QR, cannot overwrite or approve',async()=>{const [id]=await issue();const client=db();const name=()=>{const batch=writeBatch(client);batch.update(r(client,'tickets',id),{buyer:{name:'Cliente',source:'buyer',registeredAt:serverTimestamp(),consentVersion:'2026-10-name-v1'}});batch.update(r(client,'passes',id),{name:'Cliente',registered:true});return batch.commit();};await assertSucceeds(name());await assertFails(name());const ticket=(await getDoc(r(db('admin'),'tickets',id))).data();assert.equal(ticket.status,'pending');assert.equal(ticket.sellerId,'seller');assert.equal(ticket.buyer.source,'buyer');});
test('door admits approved ticket only once and cannot list buyers',async()=>{const [id]=await issue();const client=db('door');const admit=()=>runTransaction(client,async tx=>{const t=await tx.get(r(client,'tickets',id));if(t.data().status!=='valid')throw new Error('not valid');tx.update(r(client,'tickets',id),{status:'used',usedAt:serverTimestamp(),validatedBy:'door'});tx.update(r(client,'passes',id),{status:'used'});});await assert.rejects(admit());await approve(id);const results=await Promise.allSettled([admit(),admit()]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal((await getDoc(r(db(),'publicStats','sales'))).data().approved,1);await assertFails(getDocs(collection(client,'shadowfest_live/2026/tickets')));});
test('revoked seller loses reads and writes and supreme role is immutable',async()=>{const [id]=await issue();await updateDoc(r(db('admin'),'staff','seller'),{active:false,revokedAt:serverTimestamp()});await assertFails(getDoc(r(db('seller'),'tickets',id)));await assertFails(issue());await assertFails(updateDoc(r(db('admin'),'staff','admin'),{active:false,revokedAt:serverTimestamp()}));});
test('cancelling approved ticket reverses count; pending cancellation does not',async()=>{const [id,pending]=await issue('seller',6);await approve(id);const client=db('admin'),batch=writeBatch(client);batch.update(r(client,'tickets',id),{status:'cancelled',cancelledAt:serverTimestamp(),cancelledBy:'admin'});batch.update(r(client,'passes',id),{status:'cancelled'});batch.set(r(client,'meta','sales'),{approved:0,initialSold:110,lastTicket:id,updatedAt:serverTimestamp()});batch.set(r(client,'publicStats','sales'),{approved:0,initialSold:110,updatedAt:serverTimestamp()});await assertSucceeds(batch.commit());const next=writeBatch(client);next.update(r(client,'tickets',pending),{status:'cancelled',cancelledAt:serverTimestamp(),cancelledBy:'admin'});next.update(r(client,'passes',pending),{status:'cancelled'});await assertSucceeds(next.commit());assert.equal((await getDoc(r(db(),'publicStats','sales'))).data().approved,0);});

test('batch of ten stays pending and short codes resolve only for staff or their seller',async()=>{const ids=await issue('seller',10);assert.equal(ids.length,10);const first=(await getDoc(r(db('seller'),'tickets',ids[0]))).data();assert.match(first.shortCode,/^[A-HJ-NP-Z2-9]{6}$/);await assertSucceeds(getDoc(r(db('door'),'codes',first.shortCode)));await assertFails(getDoc(r(db(),'codes',first.shortCode)));await assertFails(getDoc(r(db('other'),'codes',first.shortCode)));await assertFails(getDocs(collection(db('door'),'shadowfest_live/2026/codes')));await assertFails(updateDoc(r(db('seller'),'codes',first.shortCode),{token:ids[1]}));await assertFails(updateDoc(r(db('seller'),'tickets',ids[0]),{shortCode:'K7M9Q2'}));assert.equal((await getDocs(query(collection(db('seller'),'shadowfest_live/2026/tickets'),where('sellerId','==','seller')))).size,10);});
